[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_betting_dapp = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
solana_betting_dapp = "D67EtouGnA8zrF4U3NLijdAfm8ztfXTnLvLeeXiRMhBe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "C:\\Users\\rooster\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
